FROM gliderlabs/alpine:3.3
MAINTAINER Bryan Liles <bryanliles@gmail.com>

EXPOSE 8889

RUN apk --update --no-cache  add ca-certificates iptables
COPY cmd/dolb-agent/dolb-agent /

ENTRYPOINT /dolb-agent
